# Generated by Django 4.2.6 on 2023-11-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_category_recipes_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='alc',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
